# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cassandra_object}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Koziarski"]
  s.date = %q{2009-10-18}
  s.description = %q{Gives you most of the familiarity of ActiveRecord, but with the scalability of cassandra.}
  s.email = %q{michael@koziarski.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "lib/cassandra_object.rb",
     "lib/cassandra_object/associations.rb",
     "lib/cassandra_object/associations/one_to_many.rb",
     "lib/cassandra_object/associations/one_to_one.rb",
     "lib/cassandra_object/attributes.rb",
     "lib/cassandra_object/base.rb",
     "lib/cassandra_object/callbacks.rb",
     "lib/cassandra_object/collection.rb",
     "lib/cassandra_object/cursor.rb",
     "lib/cassandra_object/dirty.rb",
     "lib/cassandra_object/identity.rb",
     "lib/cassandra_object/identity/abstract_key_factory.rb",
     "lib/cassandra_object/identity/key.rb",
     "lib/cassandra_object/identity/natural_key_factory.rb",
     "lib/cassandra_object/identity/uuid_key_factory.rb",
     "lib/cassandra_object/indexes.rb",
     "lib/cassandra_object/migrations.rb",
     "lib/cassandra_object/persistence.rb",
     "lib/cassandra_object/serialization.rb",
     "lib/cassandra_object/validation.rb",
     "test/basic_scenarios_test.rb",
     "test/config/cassandra.in.sh",
     "test/config/log4j.properties",
     "test/config/storage-conf.xml",
     "test/connection.rb",
     "test/cursor_test.rb",
     "test/dirty_test.rb",
     "test/fixture_models.rb",
     "test/identity/natural_key_factory_test.rb",
     "test/index_test.rb",
     "test/migration_test.rb",
     "test/one_to_many_associations_test.rb",
     "test/test_helper.rb",
     "test/validation_test.rb",
     "vendor/activemodel/CHANGELOG",
     "vendor/activemodel/CHANGES",
     "vendor/activemodel/README",
     "vendor/activemodel/Rakefile",
     "vendor/activemodel/examples/validations.rb",
     "vendor/activemodel/lib/active_model.rb",
     "vendor/activemodel/lib/active_model/attribute_methods.rb",
     "vendor/activemodel/lib/active_model/conversion.rb",
     "vendor/activemodel/lib/active_model/deprecated_error_methods.rb",
     "vendor/activemodel/lib/active_model/dirty.rb",
     "vendor/activemodel/lib/active_model/errors.rb",
     "vendor/activemodel/lib/active_model/locale/en.yml",
     "vendor/activemodel/lib/active_model/naming.rb",
     "vendor/activemodel/lib/active_model/observing.rb",
     "vendor/activemodel/lib/active_model/serialization.rb",
     "vendor/activemodel/lib/active_model/serializers/json.rb",
     "vendor/activemodel/lib/active_model/serializers/xml.rb",
     "vendor/activemodel/lib/active_model/state_machine.rb",
     "vendor/activemodel/lib/active_model/state_machine/event.rb",
     "vendor/activemodel/lib/active_model/state_machine/machine.rb",
     "vendor/activemodel/lib/active_model/state_machine/state.rb",
     "vendor/activemodel/lib/active_model/state_machine/state_transition.rb",
     "vendor/activemodel/lib/active_model/test_case.rb",
     "vendor/activemodel/lib/active_model/validations.rb",
     "vendor/activemodel/lib/active_model/validations/acceptance.rb",
     "vendor/activemodel/lib/active_model/validations/confirmation.rb",
     "vendor/activemodel/lib/active_model/validations/exclusion.rb",
     "vendor/activemodel/lib/active_model/validations/format.rb",
     "vendor/activemodel/lib/active_model/validations/inclusion.rb",
     "vendor/activemodel/lib/active_model/validations/length.rb",
     "vendor/activemodel/lib/active_model/validations/numericality.rb",
     "vendor/activemodel/lib/active_model/validations/presence.rb",
     "vendor/activemodel/lib/active_model/validations/with.rb",
     "vendor/activemodel/lib/active_model/validations_repair_helper.rb",
     "vendor/activemodel/lib/activemodel.rb",
     "vendor/activemodel/test/cases/helper.rb",
     "vendor/activemodel/test/cases/naming_test.rb",
     "vendor/activemodel/test/cases/observing_test.rb",
     "vendor/activemodel/test/cases/serializeration/json_serialization_test.rb",
     "vendor/activemodel/test/cases/serializeration/xml_serialization_test.rb",
     "vendor/activemodel/test/cases/state_machine/event_test.rb",
     "vendor/activemodel/test/cases/state_machine/machine_test.rb",
     "vendor/activemodel/test/cases/state_machine/state_test.rb",
     "vendor/activemodel/test/cases/state_machine/state_transition_test.rb",
     "vendor/activemodel/test/cases/state_machine_test.rb",
     "vendor/activemodel/test/cases/tests_database.rb",
     "vendor/activemodel/test/cases/validations/acceptance_validation_test.rb",
     "vendor/activemodel/test/cases/validations/conditional_validation_test.rb",
     "vendor/activemodel/test/cases/validations/confirmation_validation_test.rb",
     "vendor/activemodel/test/cases/validations/exclusion_validation_test.rb",
     "vendor/activemodel/test/cases/validations/format_validation_test.rb",
     "vendor/activemodel/test/cases/validations/i18n_generate_message_validation_test.rb",
     "vendor/activemodel/test/cases/validations/i18n_validation_test.rb",
     "vendor/activemodel/test/cases/validations/inclusion_validation_test.rb",
     "vendor/activemodel/test/cases/validations/length_validation_test.rb",
     "vendor/activemodel/test/cases/validations/numericality_validation_test.rb",
     "vendor/activemodel/test/cases/validations/presence_validation_test.rb",
     "vendor/activemodel/test/cases/validations/with_validation_test.rb",
     "vendor/activemodel/test/cases/validations_test.rb",
     "vendor/activemodel/test/config.rb",
     "vendor/activemodel/test/fixtures/topics.yml",
     "vendor/activemodel/test/models/contact.rb",
     "vendor/activemodel/test/models/custom_reader.rb",
     "vendor/activemodel/test/models/developer.rb",
     "vendor/activemodel/test/models/person.rb",
     "vendor/activemodel/test/models/reply.rb",
     "vendor/activemodel/test/models/topic.rb",
     "vendor/activemodel/test/schema.rb",
     "vendor/activesupport/lib/active_support/concern.rb",
     "vendor/activesupport/lib/active_support/core_ext/array/wrap.rb",
     "vendor/activesupport/lib/active_support/core_ext/object/blank.rb",
     "vendor/activesupport/lib/active_support/core_ext/object/tap.rb",
     "vendor/activesupport/lib/active_support/dependency_module.rb"
  ]
  s.homepage = %q{http://github.com/NZKoz/cassandra_object}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Maps your objects into cassandra.}
  s.test_files = [
    "test/basic_scenarios_test.rb",
     "test/connection.rb",
     "test/cursor_test.rb",
     "test/dirty_test.rb",
     "test/fixture_models.rb",
     "test/identity/natural_key_factory_test.rb",
     "test/index_test.rb",
     "test/migration_test.rb",
     "test/one_to_many_associations_test.rb",
     "test/test_helper.rb",
     "test/validation_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.pre"])
      s.add_runtime_dependency(%q<activemodel>, [">= 3.0.pre"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0.pre"])
      s.add_dependency(%q<activemodel>, [">= 3.0.pre"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0.pre"])
    s.add_dependency(%q<activemodel>, [">= 3.0.pre"])
  end
end
